[package]
name = "wgpu-tutorial"
version = "0.1.0"
authors = ["Carl <cdba2019@mymail.pomona.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
